import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1b",
        "clever-green": "#548655",
        "error-container": "#ffdad6",
        background: "#faf9f7",
        "surface-bright": "#faf9f7",
        primary: "#135685",
        surface: "#faf9f7",
        "on-primary-container": "#97cbff",
        "inverse-on-surface": "#f1f1ef",
        "on-secondary-container": "#59002a",
        "on-surface-variant": "#41474f",
        "secondary-container": "#fc4d91",
        "surface-dim": "#dadad8",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-container": "#cca741",
        "surface-variant": "#e3e2e0",
        "primary-fixed": "#cee5ff",
        "on-secondary": "#ffffff",
        "surface-container": "#efeeec",
        "surface-container-high": "#e9e8e6",
        "surface-container-lowest": "#ffffff",
        "whatsapp-green": "#25D366",
        "secondary-fixed": "#ffd9e1",
        "surface-container-highest": "#e3e2e0",
        secondary: "#B1005A",
        error: "#ba1a1a",
        "on-surface": "#1a1c1b",
        "deep-charcoal": "#2E2D2C",
        "surface-container-low": "#f4f3f1",
        outline: "#717880",
        "outline-variant": "#c1c7d0",
        "primary-container": "#135685",
        "border-subtle": "rgba(19, 86, 133, 0.08)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        "section-gap": "5rem",
        "stack-lg": "2rem",
        "grid-gutter": "1.5rem",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
